version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redisdata:/data

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  server:
    build:
      context: .
      dockerfile: server/dockerfile
    container_name: server
    environment:
      REDIS_URL: ${REDIS_URL}
      LOAD_CASH_PASSWORD: ${LOAD_CASH_PASSWORD}
    depends_on:
      - redis
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "3000:3000"

  auth-service:
    build:
      context: .
      dockerfile: auth-service/dockerfile
    container_name: auth-service
    environment:
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - redis
    working_dir: /usr/src/app
    command: npm start

  db-service:
    build:
      context: .
      dockerfile: db-service/dockerfile
    container_name: db-service
    environment:
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - redis
      - postgres
    working_dir: /usr/src/app
    command: npm start

  tx-processor:
    build:
      context: .
      dockerfile: tx-processor/dockerfile
    container_name: tx-processor
    environment:
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis
    working_dir: /usr/src/app
    command: npm start

volumes:
  pgdata:
  redisdata:
