FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json of tx-processor
COPY tx-processor/package.json ./

# Create the directory for common and copy the package.json
RUN mkdir -p /usr/src/common
COPY common/package.json /usr/src/common/

# Install dependencies
RUN npm install
RUN npm install --prefix /usr/src/common/

# Copy the rest of the application code
COPY tx-processor/ ./
COPY common/ /usr/src/common/

# Command to run your app
CMD ["npm", "start"]
