FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

COPY tx-processor/package.json /usr/src/app

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY tx-processor/ /usr/src/app

# Copy the common directory from the context
COPY ../common /usr/src/common

# Command to run your app
CMD ["npm", "start"]
