export const TRANSACTION_PRE_PROCESSOR_QUEUE = "TRANSACTION_PRE_PROCESSOR_QUEUE"
export const TRANSACTION_PRE_DB_WRITER_QUEUE = "TRANSACTION_PRE_DB_WRITER_QUEUE"
export const SIGNUP_USER_QUEUE = "SIGNUP_USER_QUEUE"