FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

COPY db-service/package.json /usr/src/app

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY db-service/ /usr/src/app

# Copy the common directory from the context
COPY common /usr/src/common

# Generate prisma clients
RUN npx prisma generate

# Command to run your app
CMD ["npm", "start"]